#!/usr/bin/env bash
# setup-wireguard.sh — WireGuard admin-plane provisioning
# Provisioning baseline: PROV-003 (VPN-only admin plane)
#
# PURPOSE
# -------
# Installs WireGuard, writes the device interface config from environment
# variables (or a pre-placed /etc/wireguard/wg0.conf), locks down file
# permissions, and enables the wg-quick@wg0 systemd unit.
#
# GOLDEN-IMAGE DESIGN
# -------------------
# This script contains ZERO device-specific values.  It is intended to run:
#   a) During first-boot on a freshly flashed Jetson to configure the VPN
#      plane, OR
#   b) As part of a re-provisioning pass on any unit in the field.
#
# Device identity (private key, VPN IP) must be supplied via env vars or by
# pre-staging /etc/wireguard/wg0.conf before running this script.
#
# REQUIRED ENVIRONMENT VARIABLES (when not pre-staging wg0.conf)
# --------------------------------------------------------------
#   WG_DEVICE_PRIVATE_KEY    — base64 WireGuard private key for this device
#   WG_DEVICE_VPN_IP         — VPN IP assigned to this device (e.g. 10.10.0.2)
#   WG_ADMIN_PUBLIC_KEY      — admin server's WireGuard public key
#   WG_PRESHARED_KEY         — preshared key (PSK) for this peer pair
#   WG_ADMIN_ENDPOINT        — admin server WAN address or DDNS hostname
#
# OPTIONAL
#   WG_VPN_SUBNET            — AllowedIPs for the VPN (default: 10.10.0.0/24)
#   WG_PORT                  — admin server UDP port         (default: 51820)
#   WG_ADMIN_SSH_PORT        — local SSH port to restrict to wg0 (default: 2222)
#   WG_KEEPALIVE             — PersistentKeepalive seconds   (default: 25)
#
# USAGE
# -----
#   # Option A — env-var driven (typical fleet provisioning):
#   export WG_DEVICE_PRIVATE_KEY="..."
#   export WG_DEVICE_VPN_IP="10.10.0.5"
#   ...
#   sudo -E ./setup-wireguard.sh
#
#   # Option B — pre-staged config (offline provisioning):
#   sudo cp /path/to/filled-wg0.conf /etc/wireguard/wg0.conf
#   sudo chmod 600 /etc/wireguard/wg0.conf
#   sudo ./setup-wireguard.sh   # skips config generation; just installs + enables

set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
WG_VPN_SUBNET="${WG_VPN_SUBNET:-10.10.0.0/24}"
WG_PORT="${WG_PORT:-51820}"
WG_ADMIN_SSH_PORT="${WG_ADMIN_SSH_PORT:-2222}"
WG_KEEPALIVE="${WG_KEEPALIVE:-25}"
WG_CONF="/etc/wireguard/wg0.conf"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log()  { echo "[wg-setup] $*"; }
die()  { echo "[wg-setup] ERROR: $*" >&2; exit 1; }
need_root() { [[ "$(id -u)" -eq 0 ]] || die "Must run as root (use sudo -E)"; }

# ---------------------------------------------------------------------------
# 1. Privilege check
# ---------------------------------------------------------------------------
need_root

# ---------------------------------------------------------------------------
# 2. Install WireGuard kernel module + tools
# ---------------------------------------------------------------------------
log "Installing WireGuard..."
if command -v apt-get &>/dev/null; then
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        wireguard wireguard-tools
elif command -v dnf &>/dev/null; then
    dnf install -y wireguard-tools
else
    die "Unsupported package manager — install wireguard-tools manually"
fi

# ---------------------------------------------------------------------------
# 3. Create /etc/wireguard with tight permissions (if absent)
# ---------------------------------------------------------------------------
install -d -m 700 /etc/wireguard

# ---------------------------------------------------------------------------
# 4. Generate or validate wg0.conf
# ---------------------------------------------------------------------------
if [[ -f "${WG_CONF}" ]]; then
    log "Pre-staged ${WG_CONF} found — skipping config generation"
    # Verify no placeholder tokens remain
    if grep -qE '<[A-Z_]+>' "${WG_CONF}"; then
        die "${WG_CONF} still contains <PLACEHOLDER> tokens — fill them in first"
    fi
else
    log "Generating ${WG_CONF} from environment variables..."

    # Validate required vars
    for var in WG_DEVICE_PRIVATE_KEY WG_DEVICE_VPN_IP \
                WG_ADMIN_PUBLIC_KEY WG_PRESHARED_KEY WG_ADMIN_ENDPOINT; do
        [[ -n "${!var:-}" ]] || die "Required env var \$${var} is not set"
    done

    cat > "${WG_CONF}" <<EOF
# WireGuard interface — adaptive-advertisement appliance
# Generated by setup-wireguard.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# PROV-003: VPN-only admin plane

[Interface]
PrivateKey = ${WG_DEVICE_PRIVATE_KEY}
Address    = ${WG_DEVICE_VPN_IP}/32

# Block SSH from non-VPN interfaces while WireGuard is up
PreUp    = iptables -A INPUT ! -i wg0 -p tcp --dport ${WG_ADMIN_SSH_PORT} -j DROP 2>/dev/null || true
PostDown = iptables -D INPUT ! -i wg0 -p tcp --dport ${WG_ADMIN_SSH_PORT} -j DROP 2>/dev/null || true

[Peer]
PublicKey           = ${WG_ADMIN_PUBLIC_KEY}
PresharedKey        = ${WG_PRESHARED_KEY}
Endpoint            = ${WG_ADMIN_ENDPOINT}:${WG_PORT}
AllowedIPs          = ${WG_VPN_SUBNET}
PersistentKeepalive = ${WG_KEEPALIVE}
EOF
fi

# ---------------------------------------------------------------------------
# 5. Lock down config permissions
# ---------------------------------------------------------------------------
chmod 600 "${WG_CONF}"
chown root:root "${WG_CONF}"
log "Permissions set: 600 root:root on ${WG_CONF}"

# ---------------------------------------------------------------------------
# 6. Enable and start the WireGuard interface
# ---------------------------------------------------------------------------
log "Enabling wg-quick@wg0..."
systemctl enable wg-quick@wg0

log "Starting wg-quick@wg0..."
systemctl start wg-quick@wg0

# Brief wait then status check
sleep 2
if wg show wg0 &>/dev/null; then
    log "WireGuard interface wg0 is UP"
    wg show wg0
else
    die "wg0 failed to come up — check 'journalctl -u wg-quick@wg0'"
fi

log "WireGuard provisioning complete."
