"""
Fallback bundle — the on-device asset rendered when no approved manifest is active.

The fallback bundle is:
- Validated at startup before any other service dependency is checked.
- Always present on-device; it must never require a network fetch.
- Displayed in FALLBACK state (startup, connection loss) and SAFE_MODE.

Never-blank invariant starts here: if validate() fails, main.py aborts before
any display driver is initialised, preventing a blank/black screen boot.

Asset selection
---------------
Assets are discovered from two directories, in priority order:

    FALLBACK_BUNDLE_PATH  (default: /app/fallback_bundle in the container)
        Assets committed alongside the service source or copied in at build time.
        A ``fallback-builtin.png`` (solid-colour slate, generated by the
        Dockerfile) is always present here as the last resort.

    FALLBACK_LIBRARY_PATH  (default: /data/fallback-library, runtime volume)
        Client-supplied assets mounted at deploy time.  Drop PNGs / MP4s into
        this directory and the player will discover and display them automatically.
        Intended for "well-performing ad" selection — updated without rebuilding
        the container image.

Selection priority (highest → lowest):

    1. Explicit override — ``FALLBACK_ASSET_NAME`` env var is non-empty.
       Searches FALLBACK_BUNDLE_PATH first, then FALLBACK_LIBRARY_PATH.

    2. ``_selected`` marker in FALLBACK_LIBRARY_PATH
       File contains a single asset filename (no path separators).  Write from
       dashboard-api or an ops script to promote a library asset as the active
       fallback without restarting the player.

    3. ``_selected`` marker in FALLBACK_BUNDLE_PATH
       Same mechanism; lower priority than the library marker.

    4. First non-builtin file in FALLBACK_BUNDLE_PATH (alphabetical).
       Any PNG/JPG/MP4/WEBM/HTML placed in services/player/fallback_bundle/
       and rebuilt into the image is auto-selected here.

    5. First file in FALLBACK_LIBRARY_PATH (alphabetical).
       Files mounted at runtime are discovered automatically.

    6. Built-in slate — ``fallback-builtin.png`` (always present in image).
       Dark-navy 1920×1080 PNG generated at Dockerfile build time. Only shown
       when nothing else is available.

Hot-swap (library selection changes)
-------------------------------------
Call ``refresh()`` periodically (see FALLBACK_REFRESH_INTERVAL_S).  If the
active selection has changed — e.g., a new ``_selected`` marker was written by
dashboard-api, or a new file was added to the library — ``refresh()`` returns
True and the caller should re-issue ``show_fallback``.

Supported asset types
---------------------
image : .jpg .jpeg .png
video : .mp4 .webm
html  : .html
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from . import config

log = logging.getLogger(__name__)

_EXT_TO_TYPE: dict[str, str] = {
    ".jpg": "image",
    ".jpeg": "image",
    ".png": "image",
    ".mp4": "video",
    ".webm": "video",
    ".html": "html",
}

# Filenames that are never treated as playable assets
_RESERVED: frozenset[str] = frozenset({
    "_selected",
    ".gitkeep",
    "fallback-builtin.png",  # last-resort built-in; skipped in auto-discovery
})

BUILTIN_NAME = "fallback-builtin.png"
SELECTED_MARKER = "_selected"


class FallbackBundleMissingError(RuntimeError):
    """Raised when no fallback asset can be located."""


class FallbackBundle:
    """
    Manages the active fallback asset.

    Call ``validate()`` once at startup before any renderer call.
    Call ``refresh()`` periodically to pick up library / selection changes.
    """

    def __init__(self) -> None:
        self._asset_path: Optional[str] = None
        self._asset_type: Optional[str] = None
        self._source: str = "uninitialised"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def validate(self) -> None:
        """
        Select and validate the active fallback asset.
        Raises FallbackBundleMissingError if no asset can be found at all.
        Must be called before any renderer call (startup step 1).
        """
        self._resolve()
        if self._asset_path is None:
            bundle = config.FALLBACK_BUNDLE_PATH
            library = config.FALLBACK_LIBRARY_PATH or "(not configured)"
            raise FallbackBundleMissingError(
                "No fallback asset found.\n"
                f"  Bundle directory : {bundle}\n"
                f"  Library directory: {library}\n"
                f"  Supported types  : {sorted(_EXT_TO_TYPE.keys())}\n\n"
                "Options:\n"
                "  1. Place an asset in services/player/fallback_bundle/ and rebuild the image.\n"
                "  2. Mount a volume at FALLBACK_LIBRARY_PATH and place an asset there.\n"
                "  3. Set FALLBACK_ASSET_NAME to an explicit filename."
            )

    def refresh(self) -> bool:
        """
        Re-evaluate the asset selection without restarting the player.

        Returns True if the active asset path changed (caller should re-issue
        show_fallback if the player is in FALLBACK or SAFE_MODE state).
        Safe to call from the asyncio event loop.
        """
        prev_path = self._asset_path
        try:
            self._resolve()
        except Exception as exc:  # pragma: no cover — defensive
            log.warning("fallback refresh error (keeping current selection): %s", exc)
        changed = self._asset_path != prev_path
        if changed:
            log.info(
                "fallback selection changed: %r → %r (source=%s)",
                prev_path,
                self._asset_path,
                self._source,
            )
        return changed

    def list_available(self) -> list[dict]:
        """
        Enumerate all available fallback assets across bundle and library dirs.
        Returns list of dicts: {path, asset_type, source, is_active}.
        Used by dashboard-api to populate the fallback asset picker.
        """
        results: list[dict] = []
        active = self._asset_path

        dirs = [
            ("bundle", Path(config.FALLBACK_BUNDLE_PATH)),
        ]
        if config.FALLBACK_LIBRARY_PATH:
            dirs.append(("library", Path(config.FALLBACK_LIBRARY_PATH)))

        for source_label, directory in dirs:
            if not directory.exists():
                continue
            for p in sorted(directory.iterdir()):
                ext = p.suffix.lower()
                if ext not in _EXT_TO_TYPE:
                    continue
                results.append({
                    "path": str(p),
                    "name": p.name,
                    "asset_type": _EXT_TO_TYPE[ext],
                    "source": source_label,
                    "is_active": str(p) == active,
                })

        return results

    @property
    def asset_path(self) -> str:
        if self._asset_path is None:
            raise FallbackBundleMissingError("validate() has not been called.")
        return self._asset_path

    @property
    def asset_type(self) -> str:
        if self._asset_type is None:
            raise FallbackBundleMissingError("validate() has not been called.")
        return self._asset_type

    @property
    def source(self) -> str:
        """Which selection mechanism produced the current asset (for diagnostics)."""
        return self._source

    # ------------------------------------------------------------------
    # Private — selection logic
    # ------------------------------------------------------------------

    def _resolve(self) -> None:
        bundle_dir = Path(config.FALLBACK_BUNDLE_PATH)
        library_dir = (
            Path(config.FALLBACK_LIBRARY_PATH)
            if config.FALLBACK_LIBRARY_PATH
            else None
        )

        # 1. Explicit override via FALLBACK_ASSET_NAME env var
        explicit_name = config.FALLBACK_ASSET_NAME
        if explicit_name:
            for search_dir in filter(None, [bundle_dir, library_dir]):
                p = search_dir / explicit_name
                if p.exists() and p.suffix.lower() in _EXT_TO_TYPE:
                    self._set(p, "explicit")
                    return
            log.warning(
                "FALLBACK_ASSET_NAME=%r not found in bundle or library — "
                "falling through to auto-discovery",
                explicit_name,
            )

        # 2. _selected marker in library (runtime hot-swap, highest dynamic priority)
        if library_dir and library_dir.exists():
            if self._try_selected_marker(library_dir, library_dir, "selected-library"):
                return

        # 3. _selected marker in bundle (build-time default override)
        if self._try_selected_marker(bundle_dir, library_dir, "selected-bundle"):
            return

        # 4. First non-reserved asset in bundle (alphabetical)
        for p in sorted(bundle_dir.glob("*")):
            if p.name in _RESERVED:
                continue
            if p.suffix.lower() in _EXT_TO_TYPE:
                self._set(p, "bundle-auto")
                return

        # 5. First asset in library (alphabetical)
        if library_dir and library_dir.exists():
            for p in sorted(library_dir.glob("*")):
                if p.name == SELECTED_MARKER:
                    continue
                if p.suffix.lower() in _EXT_TO_TYPE:
                    self._set(p, "library-auto")
                    return

        # 6. Built-in slate (always present in container image)
        builtin = bundle_dir / BUILTIN_NAME
        if builtin.exists():
            self._set(builtin, "builtin")
            return

        # Nothing found — validate() will raise
        self._asset_path = None
        self._asset_type = None
        self._source = "none"

    def _try_selected_marker(
        self,
        marker_dir: Path,
        fallback_search_dir: Optional[Path],
        source_label: str,
    ) -> bool:
        """
        Read the ``_selected`` file from *marker_dir*.  If it names a valid
        asset (resolved in *marker_dir* first, then *fallback_search_dir*),
        call ``_set`` and return True; otherwise return False.
        """
        marker = marker_dir / SELECTED_MARKER
        if not marker.exists():
            return False

        name = marker.read_text(encoding="utf-8").strip()
        if not name or "/" in name or "\\" in name:
            # Reject path traversal attempts
            log.warning("_selected in %s contains invalid filename %r — ignored", marker_dir, name)
            return False

        search_dirs = [marker_dir]
        if fallback_search_dir and fallback_search_dir != marker_dir:
            search_dirs.append(fallback_search_dir)

        for d in search_dirs:
            p = d / name
            if p.exists() and p.suffix.lower() in _EXT_TO_TYPE:
                self._set(p, source_label)
                return True

        log.warning(
            "_selected in %s references %r but file not found in %s",
            marker_dir,
            name,
            [str(d) for d in search_dirs],
        )
        return False

    def _set(self, path: Path, source: str) -> None:
        self._asset_path = str(path)
        self._asset_type = _EXT_TO_TYPE[path.suffix.lower()]
        self._source = source
        log.info(
            "fallback asset selected: path=%s type=%s source=%s",
            path,
            self._asset_type,
            source,
        )
